PYTHON ?= python3

install:
	$(PYTHON) -m pip install -r requirements.txt

run:
	$(PYTHON) cli.py

safe:
	$(PYTHON) cli.py --query 1

full:
	$(PYTHON) cli.py --query 2

demo:
	$(PYTHON) cli.py --demo
